### ISSUE TITLE
iCaRL first task evaluation while training

### ISSUE THREAD

**Issue by jmin0530** [ContinualAI/avalanche#1299]
When I use iCaRL strategy, the error below appears.
'''
-- Starting eval on experience 0 (Task 0) from train stream --
0it [00:00, ?it/s]Traceback (most recent call last):
  File "icarl_example_medmnist.py", line 279, in <module>
    run_experiment(config)
  File "icarl_example_medmnist.py", line 237, in run_experiment
    strategy.train(exp, num_workers=4)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 146, intrain
    super().train(experiences, eval_streams, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base.py", line 116, in train
    self._train_exp(self.experience, eval_streams, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 265, in_train_exp
    self._after_training_epoch(**kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 394, in_after_training_epoch
    trigger_plugins(self, "after_training_epoch", **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/utils.py", line 35, in trigger_plugins
    getattr(p, event)(strategy, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 515, inafter_training_epoch
    self._maybe_peval(strategy, strategy.clock.train_exp_epochs,
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 508, in_maybe_peval
    self._peval(strategy, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 504, in_peval
    strategy.eval(el, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 161, ineval
    super().eval(exp_list, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base.py", line 153, in eval
    self._eval_exp(**kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 171, in_eval_exp
    self.eval_epoch(**kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/base_sgd.py", line 213, ineval_epoch
    self.mb_output = self.forward()
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/training/templates/problem_type/supervised_problem.py", line 27, in forward
    return avalanche_forward(self.model, self.mb_x, self.mb_task_id)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/models/utils.py", line 13, in avalanche_forward
    return model(x)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/models/dynamic_modules.py", line 449, in forward
    return self.classifier(x)
  File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  **File "/opt/conda/envs/jungmin_miccai/lib/python3.8/site-packages/avalanche/models/ncm_classifier.py", line 23, in forward
    sqd = torch.cdist(self.class_means[:, :].T, pred_inter)
TypeError: 'NoneType' object is not subscriptable**
'''

In my opinion, 'NCMClassifier', which works during evaluation, does not work in the first task, because self.class_means is of type 'None' in the first task. self.class_means is calculated after learning each task, and for this reason, it seems that iCaRL cannot be evaluated in the first task.

My code is below.
~~~
   benchmark_nc = nc_benchmark(
        train_dataset=train_set,
        test_dataset=test_set,
        n_experiences=config.nb_exp,
        per_exp_classes=config.first_task_classes,
        task_labels=False,
        seed=config.seed,
        shuffle=False,
        fixed_class_order=config.fixed_class_order
    )
    
    
    benchmark = benchmark_with_validation_stream(
        benchmark_instance = benchmark_nc,
        validation_size = config.val_split,
        shuffle = False
        )
    
    benchmark.n_classes_per_exp = benchmark_nc.n_classes_per_exp
    benchmark.classes_order = benchmark_nc.classes_order

    interactive_logger = InteractiveLogger()
    wandb_logger = WandBLogger(
        project_name=config.project, run_name=config.run)

    eval_plugin = EvaluationPlugin(
        accuracy_metrics(
            minibatch=True,
            epoch=True,
            epoch_running=True,
            experience=True,
            stream=True,
        ),
        loss_metrics(
            minibatch=True,
            epoch=True,
            epoch_running=True,
            experience=True,
            stream=True,
        ),
        forgetting_metrics(experience=True, stream=True),
        confusion_matrix_metrics(
            stream=True, wandb=True, class_names=[str(i) for i in range(config.num_classes)]
        ),
        loggers=[interactive_logger, wandb_logger],
    )

    model: IcarlNet = make_icarl_net(num_classes=config.num_classes)
    model.apply(initialize_icarl_net)

    optim = SGD(
        model.parameters(),
        lr=config.lr_base,
        weight_decay=config.wght_decay,
        momentum=0.9,
    )
    sched = LRSchedulerPlugin(
        MultiStepLR(optim, config.lr_milestones, gamma=1.0 / config.lr_factor)
    )
#     earlystop = EarlyStoppingPlugin(patience=7, val_stream_name='valid_stream', peval_mode='epoch', margin=0.001, verbose=True)
    
    if config.icarl:
        strategy = ICaRL(
            model.feature_extractor,
            model.classifier,
            optim,
            config.memory_size,
            buffer_transform=None,
            fixed_memory=True,
            train_mb_size=config.batch_size,
            train_epochs=config.epochs,
            eval_mb_size=config.batch_size,
            plugins=[sched],
            device=device,
            evaluator=eval_plugin,
            eval_every=1,
        )
    else:
        criterion = torch.nn.CrossEntropyLoss()
        strategy = Naive(
            model,
            optim,
            criterion,
            train_epochs=config.epochs,
            device=device,
            train_mb_size=config.batch_size,
            plugins=[sched],
            evaluator=eval_plugin,
            eval_every=1,
        )

    for i, (exp, valid_exp) in enumerate(zip(benchmark.train_stream, benchmark.valid_stream)):
        eval_exps = [e for e in benchmark.test_stream][: i + 1]
        strategy.train(exp,eval_streams=[valid_exp],num_workers=4)
        strategy.eval(eval_exps, num_workers=4)
~~~

**Comment by Melika-Ayoughi** [comment]
This is also the error that I got. I wanted to calculate the forward transfer metrics and for that, the strategy.eval_every needs to be bigger than -1. Did you find a workaround for this issue?

**Comment by AntonioCarta** [comment]
@AndreaCossu is this fixed now with the latest changes to NCM?

**Comment by AndreaCossu** [comment]
This should be fixed now
