### ISSUE TITLE
How to use Lookahead Optimizer?

### ISSUE THREAD

**Issue by pzSuen** [ContinualAI/avalanche#1324]
[Lookahead](https://arxiv.org/pdf/1907.08610.pdf) is an optimizer orthogonal to previous optimizers (e.g. Adam, sgd) and iteratively updates two sets of weights.
I try to use Lookahead Optimizer with Adam optimizer, but a problem occurs as follows: 

```
Traceback (most recent call last):
  File "/home/Name/Code/project23/SingleTraining/ST-Adam.py", line 184, in <module>
    main(args, dl)
  
File "/home/Name/Code/project23/SingleTraining/ST-Adam.py", line 146, in main
    joint_train.train(train_experience, [scenario.streams['val']], num_workers=4, persistent_workers=True)
  
File "/home/Name/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/training/supervised/joint_training.py", line 142, in train
    self._before_training_exp(**kwargs)
  
File "/home/Name/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/training/templates/base_sgd.py", line 237, in _before_training_exp
    self.check_model_and_optimizer()
  
File "/home/Name/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/training/templates/observation_type/batch_observation.py", line 31, in check_model_and_optimizer
    self.make_optimizer()
  
File "/home/Name/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/training/templates/observation_type/batch_observation.py", line 27, in make_optimizer
    reset_optimizer(self.optimizer, self.model)
  
File "/home/Name/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/models/dynamic_optimizers.py", line 30, in reset_optimizer
    assert len(optimizer.param_groups) == 1

AssertionError
```

The way Lookahead Optimizer work is as [TransMIL](https://github.com/szc19990412/TransMIL/blob/main/MyOptimizer/lookahead.py).

**Comment by pzSuen** [comment]
Thank you for your answers! @AntonioCarta @HamedHemati 
I will use the Adam optimizer only.
