### ISSUE TITLE
ConcatDatasets 

### ISSUE THREAD

**Issue by malashinroman** [ContinualAI/avalanche#1525]
🐛 **Describe the bug**
Error of not getting Key in the guts of benchmarks code.

```
Traceback (most recent call last):
  File "examples/concatenated_dataset.py", line 68, in <module>
    benchmark = create_custom_mnist_scenario()
  File "examples/concatenated_dataset.py", line 58, in create_custom_mnist_scenario
    benchmark = nc_benchmark(
  File "/home/malashin/projects/opensource/avalanche/./avalanche/benchmarks/scenarios/deprecated/generators.py", line 270, in nc_benchmark
    return NCScenario(
  File "/home/malashin/projects/opensource/avalanche/./avalanche/benchmarks/scenarios/deprecated/new_classes/nc_scenario.py", line 397, in __init__
    train_tgt_idx = original_training_dataset.targets.val_to_idx[sc]
KeyError: 8
```
🐜 **To Reproduce**

```
import torch

from torchvision.datasets.mnist import MNIST, FashionMNIST
from torchvision.transforms import Compose, ToTensor

from avalanche.models import SimpleMLP
from avalanche.benchmarks.scenarios.deprecated.generators import nc_benchmark
from avalanche.training.supervised.strategy_wrappers import Naive


def create_custom_mnist_scenario():
    transform = Compose([ToTensor()])

    mnist_train = MNIST(
        "./data/mnist",
        train=True,
        download=True,
        transform=transform,
    )
    mnist_test = MNIST(
        "./data/mnist",
        train=False,
        download=True,
        transform=transform,
    )

    fmnist_train = FashionMNIST(
        "./data/mnist",
        train=True,
        download=True,
        transform=transform,
    )

    fmnist_test = FashionMNIST(
        "./data/mnist",
        train=False,
        download=True,
        transform=transform,
    )

    reproduce_bugs = True

    if reproduce_bugs:
        full_test = mnist_test + fmnist_test
        full_train = mnist_train + fmnist_train
    else:
        full_test = mnist_test
        full_train = mnist_train

    benchmark = nc_benchmark(
        full_train,
        full_test,
        n_experiences=5,
        task_labels=list(range(5)),
    )
    return benchmark


if __name__ == "__main__":
    benchmark = create_custom_mnist_scenario()

    model = SimpleMLP(hidden_size=64, hidden_layers=1)
    optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
    criterion = torch.nn.CrossEntropyLoss()

    strategy = Naive(
        model,
        optimizer,
        criterion,
    )

    for experience in benchmark.train_stream:
        strategy.train(experience)
```

🐝 **Expected behavior**
Training should start normally.

🦋 **Additional context**
I created a pull request for fixing the exact one case [(https://github.com/ContinualAI/avalanche/pull/1524)]

But expected to be reproduced in other parts of the code

**Comment by AntonioCarta** [comment]
fixed in #1524
