### ISSUE TITLE
Unit Test failing

### ISSUE THREAD

**Issue by digantamisra98** [ContinualAI/avalanche#455]
Unit Test failing because of MNIST download error. Trace: 
```
======================================================================
ERROR: test_ni_sit_type (tests.test_scenarios_typechecks.ScenariosTypeChecksTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/avalanche/avalanche/tests/test_scenarios_typechecks.py", line 43, in test_ni_sit_type
    mnist_train = MNIST('./data/mnist', train=True, download=True)
  File "/usr/share/miniconda/envs/avalanche-env/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 85, in __init__
    self.download()
  File "/usr/share/miniconda/envs/avalanche-env/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 169, in download
    raise RuntimeError("Error downloading {}".format(filename))
RuntimeError: Error downloading https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz
```

**Comment by vlomonaco** [comment]
Thanks @digantamisra98 we are aware of this and working to fix the problem. @ggraffieti will provide a definitive solution soon.

**Comment by ggraffieti** [comment]
I think we should have fixed the issue now. Is not the final fix (which will be using docker containers with the dataset pre-downloaded during tests) but I think we can close this issue now.
