### ISSUE TITLE
TypeError when running all examples except test_install.py

### ISSUE THREAD

**Issue by FedericoWong** [ContinualAI/avalanche#740]
Hi,
I'm running in a clean anaconda env with ubuntu 20.04,python3.9,cuda11.1&cudnn8.0
Upon running the examples in the folder 'avalanche', always encounter with the TypeError below:
running ewc_mnist.py：
`/home/jofferywang/anaconda3/envs/avalanche-env/bin/python /home/jofferywang/avalanche/examples/ewc_mnist.py
Traceback (most recent call last):
  File "/home/jofferywang/avalanche/examples/ewc_mnist.py", line 7, in <module>
    from avalanche.training.strategies import EWC
  File "/home/jofferywang/avalanche/avalanche/training/__init__.py", line 8, in <module>
    from .strategies import *
  File "/home/jofferywang/avalanche/avalanche/training/strategies/__init__.py", line 6, in <module>
    from .base_strategy import *
  File "/home/jofferywang/avalanche/avalanche/training/strategies/base_strategy.py", line 25, in <module>
    from avalanche.training.plugins.evaluation import default_logger
  File "/home/jofferywang/avalanche/avalanche/training/plugins/__init__.py", line 3, in <module>
    from .evaluation import EvaluationPlugin
  File "/home/jofferywang/avalanche/avalanche/training/plugins/evaluation.py", line 285, in <module>
    accuracy_metrics(minibatch=False, epoch=True, experience=True, stream=True),
  File "/home/jofferywang/avalanche/avalanche/evaluation/metrics/accuracy.py", line 344, in accuracy_metrics
    metrics.append(EpochAccuracy())
  File "/home/jofferywang/avalanche/avalanche/evaluation/metrics/accuracy.py", line 210, in __init__
    super(EpochAccuracy, self).__init__(
  File "/home/jofferywang/avalanche/avalanche/evaluation/metrics/accuracy.py", line 144, in __init__
    self._accuracy = Accuracy()
  File "/home/jofferywang/avalanche/avalanche/evaluation/metrics/accuracy.py", line 47, in __init__
    super().__init__()
  File "/home/jofferywang/anaconda3/envs/avalanche-env/lib/python3.9/typing.py", line 1083, in _no_init
    raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated
`
running ccifar10.py from avalanche.benchmarks.classic
```
Traceback (most recent call last):
  File "/home/jofferywang/avalanche/avalanche/benchmarks/classic/ccifar10.py", line 151, in <module>
    benchmark_instance = SplitCIFAR10(5)
  File "/home/jofferywang/avalanche/avalanche/benchmarks/classic/ccifar10.py", line 125, in SplitCIFAR10
    return nc_benchmark(
  File "/home/jofferywang/avalanche/avalanche/benchmarks/generators/benchmark_generators.py", line 195, in nc_benchmark
    train_dataset = AvalancheDataset(
  File "/home/jofferywang/avalanche/avalanche/benchmarks/utils/avalanche_dataset.py", line 160, in __init__
    super().__init__()
  File "/home/jofferywang/anaconda3/envs/avalanche-env/lib/python3.9/typing.py", line 1083, in _no_init
    raise TypeError('Protocols cannot be instantiated')
TypeError: Protocols cannot be instantiated
```
I assure that i had strictedly followed the instruction on the https://avalanche.continualai.org/getting-started/how-to-install. however, it seems work unlucky.Hope to your feedback,thacks!

PS : this is my installation list:
[condalist_avalanche.txt](https://github.com/ContinualAI/avalanche/files/7144198/condalist_avalanche.txt)

**Comment by FedericoWong** [comment]
[condalist_avalanche.txt](https://github.com/ContinualAI/avalanche/files/7144251/condalist_avalanche.txt)

**Comment by FedericoWong** [comment]
[condalist_avalanche.txt](https://github.com/ContinualAI/avalanche/files/7144260/condalist_avalanche.txt)
Sorry for the network delay

**Comment by vlomonaco** [comment]
Thanks @FedericoWong for reporting the issue, we will try to replicate it and report back to you!

**Comment by FedericoWong** [comment]
Well,I installed a new env with python3.8,cuda11.1&cudnn8.0 last night, and it works well.
Maybe the 'Protocols not be instantiated' problem(in python/typing package) is closely related to the python version.
![2021-09-11 11-58-57screen_shot1](https://user-images.githubusercontent.com/26487534/132935653-239f2e8b-7997-40b2-954a-181dd0670ec2.png)

Thanks @vlomonaco  for your help. It IS Just a little problem and i wish to see how to solve it in python3.9 . lol
