### ISSUE TITLE
install success but import error

### ISSUE THREAD

**Issue by pzSuen** [ContinualAI/avalanche#912]
As seen in the image,
the code  of ava.py is copied from ["putting all together"](https://avalanche.continualai.org/from-zero-to-hero-tutorial/07_putting-all-together)
![image](https://user-images.githubusercontent.com/43957007/153761490-17aa1ef9-91e7-416a-907b-3e1dad2a53ed.png)

**Comment by pzSuen** [comment]
Thank you, problem solved in this way.

But I encountered another problem when I was using dataset_benchmark.
I defined my own `dataset` in the way CIFAR10 does,
And then, I try to run the following code,
```
ava_train = AvalancheDataset(trainset, task_labels=i)
ava_test = AvalancheDataset(validset, task_labels=i)

# the size of trainset is 270, and the size of validset is 129.
```

The overall length is 270, and the last should be 269 rather than 270. I don't know why this happened.

```
Traceback (most recent call last):
  File "/home/pzsuen/Code/ava/wsi_cls.py", line 55, in <module>
    ava_train = AvalancheDataset(train, task_labels=i)
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/benchmarks/utils/avalanche_dataset.py", line 237, in __init__
    self._optimize_targets()
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/benchmarks/utils/avalanche_dataset.py", line 989, in _optimize_targets
    self.targets = optimize_sequence(self.targets)
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/benchmarks/utils/dataset_utils.py", line 371, in optimize_sequence
    return list(sequence)
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/_collections_abc.py", line 883, in __iter__
    v = self[i]
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/avalanche/benchmarks/utils/dataset_utils.py", line 54, in __getitem__
    element = self._targets[subset_idx]
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/pandas/core/series.py", line 990, in _get_value
    loc = self.index.get_loc(label)
  File "/home/pzsuen/.conda/envs/avalanche/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 270
```
