### ISSUE TITLE
It seems that I am experiencing an error in Quick Example?

### ISSUE THREAD

**Issue by weizh588** [ContinualAI/avalanche#944]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ffbee24c3a0>
Traceback (most recent call last):
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1283, in _shutdown_workers
    self._pin_memory_thread.join()
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/threading.py", line 1008, in join
    raise RuntimeError("cannot join current thread")
**RuntimeError: cannot join current thread**
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ffbee24c3a0>
Traceback (most recent call last):
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
  0%|                                          | 1/1875 [00:00<27:34,  1.13it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ffbee24c3a0>
Traceback (most recent call last):
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
  0%|                                          | 2/1875 [00:01<18:38,  1.68it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ffbee24c3a0>
Traceback (most recent call last):
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
  0%|                                          | 3/1875 [00:01<16:38,  1.87it/s][W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
Traceback (most recent call last):
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ffbee24c3a0>
Traceback (most recent call last):
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1320, in _shutdown_workers
    if w.is_alive():
  File "/home/wzh21/.conda/envs/clvision/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
**AssertionError: can only test a child process**

**Comment by AntonioCarta** [comment]
This is a known issue with Pytorch dataloaders on windows. You can fix it by changing `num_workers=0`. I don't think we can do anything on our side.
